# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

workspace 'QuickSecurityCodeDemo.xcworkspace'
project 'QuickSecurityCodeDemo.xcodeproj'

target 'QuickSecurityCodeDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for QuickSecurityCodeDemo
  pod 'QuickSecurityCode'
end
